name: Run Granot Scraper

on:
  # Manual trigger
  workflow_dispatch: {}

  # Scheduled trigger (UTC). Change as you like.
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

# Prevent overlapping runs (latest wins)
concurrency:
  group: granot-scraper
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scrape:
    name: Scrape & Post
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      # --- your scraper env comes from repo secrets ---
      GRANOT_BASE:   ${{ secrets.GRANOT_BASE }}
      GRANOT_NET_ID: ${{ secrets.GRANOT_NET_ID }}
      GRANOT_NET_PASS: ${{ secrets.GRANOT_NET_PASS }}
      GRANOT_USER:   ${{ secrets.GRANOT_USER }}
      GRANOT_PASS:   ${{ secrets.GRANOT_PASS }}
      GAS_ENDPOINT:  ${{ secrets.GAS_ENDPOINT }}

      # Optional knobs (set repo secrets or leave defaults)
      HEADLESS: "true"
      DEBUG:    "false"
      NET_IDLE_MS: "1500"
      RETRIES: "2"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps (prefer reproducible)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright (Chromium only) + OS deps
        run: npx playwright install --with-deps chromium

      # Small, robust retry wrapper around your script
      - name: Run scraper (retry up to 3x)
        run: |
          set -e
          for i in 1 2 3; do
            echo "Attempt $i…"
            node scrape.js && break
            echo "Attempt $i failed. Sleeping 20s…"
            sleep 20
          done

      # Upload any logs/reports you might write; safe if none exist
      - name: Upload run logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          if-no-files-found: ignore
          path: |
            playwright-report/**
            **/debug.log
            **/logs/**
            **/*.png
